lib/efossils_web/router.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.Router do
  use EfossilsWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :efossils

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout_from_session
  end
  
  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler 
    plug :put_layout_from_session
  end

  pipeline :put_session do
    plug :fetch_session
  end
  
  scope "/" do
    pipe_through :browser
    pow_routes()
    pow_extension_routes()
  end
  
  scope "/" do
    pipe_through :protected
    pow_routes()
    pow_extension_routes()
  end

  scope "/fossil", EfossilsWeb do
    pipe_through :put_session
    forward "/", Proxy.Plug
  end
  
  scope "/", EfossilsWeb do
    pipe_through :browser # Use the default browser stack
    
    get "/", PageController, :index

    get "/explore/repositories", ExploreRepositoriesController, :index
    get "/explore/repositories/:username", ExploreRepositoriesController, :index_by_username
  end

  scope "/", EfossilsWeb do
    pipe_through :protected

    get "/profile", ProfileController, :index
    put "/profile", ProfileController, :update
    get "/dashboard", PageController, :dashboard
    get "/", PageController, :dashboard
    resources "/repositories", RepositoryController do
      put "/delete", RepositoryController, :delete_repository, as: :settings
      post "/collaboration/add", RepositoryController, :collaboration_create, as: :collaboration
      delete "/collaboration/:user_id/delete", RepositoryController, :collaboration_delete, as: :collaboration
      post "/pushmirror/add", RepositoryController, :pushmirror_create, as: :pushmirror
      delete "/pushmirror/:push_mirror_id/delete", RepositoryController, :pushmirror_delete, as: :pushmirror
    end

    get "/migrate/repository", RepositoryController, :migrate_new, as: :migration
    post "/migrate/repository", RepositoryController, :migrate_create, as: :migration
  end

  scope "/api/v1", EfossilsWeb do
    pipe_through :protected
    get "/search/user", Api.V1.SearchController, :user
  end
  
  defp put_layout_from_session(conn, _) do
    if conn.assigns[:current_user] do
      Phoenix.Controller.put_layout(conn, {EfossilsWeb.Phoenix.LayoutView, :app})
    else
      Phoenix.Controller.put_layout(conn, {EfossilsWeb.Phoenix.LayoutView, :page})
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", EfossilsWeb do
  #   pipe_through :api
  # end
end

lib/efossils/repositories/push_mirror.ex
defmodule Efossils.Repositories.PushMirror do
  use Ecto.Schema
  import Ecto.Changeset


  schema "push_mirrors" do
    field :source, :string
    field :name, :string
    field :url, :string
    field :last_sync, :naive_datetime
    field :last_sync_status, :string
    belongs_to :repository, Efossils.Accounts.Repository
    timestamps()
  end

  @doc false
  def changeset(push_mirror, attrs) do
    push_mirror
    |> cast(attrs, [:name, :source, :url, :last_sync_status, :last_sync, :repository_id])
    |> validate_required([:name, :source, :url])
  end
end

lib/efossils/repositories/repositories.ex
defmodule Efossils.Repositories do
  @moduledoc """
  The Repositories context.
  """

  import Ecto.Query, warn: false
  alias Efossils.Repo

  alias Efossils.Accounts
  alias Efossils.Repositories.PushMirror

  @doc """
  Returns the list of push_mirrors.

  ## Examples

      iex> list_push_mirrors()
      [%PushMirror{}, ...]

  """
  def list_push_mirrors(repository = %Accounts.Repository{}) do
    Repo.all(from t in PushMirror, where: t.repository_id == ^repository.id)
  end

  @doc """
  Gets a single push_mirror.

  Raises `Ecto.NoResultsError` if the Push mirror does not exist.

  ## Examples

      iex> get_push_mirror!(123)
      %PushMirror{}

      iex> get_push_mirror!(456)
      ** (Ecto.NoResultsError)

  """
  def get_push_mirror!(id), do: Repo.get!(PushMirror, id)

  @doc """
  Creates a push_mirror.

  ## Examples

      iex> create_push_mirror(%{field: value})
      {:ok, %PushMirror{}}

      iex> create_push_mirror(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_push_mirror(attrs \\ %{}) do
    %PushMirror{}
    |> PushMirror.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a push_mirror.

  ## Examples

      iex> update_push_mirror(push_mirror, %{field: new_value})
      {:ok, %PushMirror{}}

      iex> update_push_mirror(push_mirror, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_push_mirror(%PushMirror{} = push_mirror, attrs) do
    push_mirror
    |> PushMirror.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a PushMirror.

  ## Examples

      iex> delete_push_mirror(push_mirror)
      {:ok, %PushMirror{}}

      iex> delete_push_mirror(push_mirror)
      {:error, %Ecto.Changeset{}}

  """
  def delete_push_mirror(%PushMirror{} = push_mirror) do
    Repo.delete(push_mirror)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking push_mirror changes.

  ## Examples

      iex> change_push_mirror(push_mirror)
      %Ecto.Changeset{source: %PushMirror{}}

  """
  def change_push_mirror(%PushMirror{} = push_mirror) do
    PushMirror.changeset(push_mirror, %{})
  end
end

lib/efossils_web/controllers/repository_controller.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.RepositoryController do
  use EfossilsWeb, :controller
  alias Efossils.Repositories
  alias Efossils.Accounts
  alias Efossils.Repo

  @readonly_capabilities "ghojr2"
  @nobody_capabilities "gjorz2"
  @default_capabilities "cdefgijkmnortuvwxy4"
  @default_capabilities_collaborator "cdefgijkmnortuvwxy4"
  @sources_migration [{"Fossil", "fossil"}, {"GIT", "git"}]
  @sources_pushmirror [{"Fossil", "fossil"}, {"GIT", "git"}]

  def allowed_owners(conn) do
    [{conn.assigns.current_user.name, conn.assigns.current_user.id}]
  end
  def new(conn, _params) do
    users = allowed_owners(conn)
    changeset = Accounts.change_repository(
      %Accounts.Repository{owner_id: conn.assigns[:current_user].id}
    )
    render(conn, "new.html",
      changeset: changeset,
      users: users,
      licenses: build_list_licenses())
  end

  
  def create(conn, %{"repository" => repository_params}) do
    users = allowed_owners(conn)

    repository_params = repository_params
    |> Map.put("owner_id", conn.assigns[:current_user].id)
    |> Accounts.Repository.prepare_attrs

    login_username = conn.assigns[:current_user].nickname
    result = Ecto.Multi.new()
    |> Ecto.Multi.run(:repository, fn repo, %{} ->
      Accounts.create_repository(repository_params)
    end)
    |> Ecto.Multi.run(:ctx, fn repo, %{repository: repository} ->
      Accounts.context_repository(repository)
    end)
    |> Ecto.Multi.run(:commands, fn repo, %{repository: repository, ctx: ctx} ->
      with {:ok, ctx} <- Efossils.Command.new_user(ctx, login_username,
        EfossilsWeb.Utils.public_id(conn.assigns[:current_user]),
        conn.assigns[:current_user].email),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "project-name", repository.name),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "project-description", repository.description),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "short-project-name", repository.nickname),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "search-doc", "1"),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "search-tkt", "1"),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "search-wiki", "1"),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "search-technote", "1"),
      {:ok, _} <- Efossils.Command.force_setting(ctx, "search-ci", "0"),
      {:ok, _} <- Efossils.Command.setting(ctx, "default-perms", "dei2"),
      {:ok, _} <- Efossils.Command.password_user(ctx,
        login_username, conn.assigns[:current_user].email),
      {:ok, _} <- Efossils.Command.capabilities_user(ctx, login_username, @default_capabilities),
      {:ok, _} <- Efossils.Command.config_import(ctx, "fossil.skin"),
      {:ok, _} <- Efossils.Command.config_import(ctx, "fossil.ticket.skin"),
      {:ok, _} <- Efossils.Command.Collaborative.append_assigned_to(ctx, login_username),
      {:ok, ctx} <- Efossils.Command.capabilities_user(ctx, "nobody", @nobody_capabilities),
        do: {:ok, ctx}
    end)
    |> Ecto.Multi.run(:update_ctx, fn repo, %{commands: ctx, repository: repository} ->
      Accounts.update_repository(repository, Enum.into(ctx, %{}))
    end)
    
    case Repo.transaction(result) do
      {:ok, %{repository: repository}} ->
        if repository_params["project_code"] != "" do
          {:ok, ctx} = Accounts.context_repository(repository)
	        Efossils.Command.force_setting(ctx, "project-code", repository_params["project_code"])
        end
        Accounts.update_repository(repository, %{"project_code" => Accounts.repository_project_code(repository)})
        conn
        |> put_flash(:info, "Repository created successfully.")
        |> redirect(to: "/dashboard")
      {:error, :commands, error, %{ctx: ctx}} ->
        Efossils.Command.delete_repository(ctx)
        changeset = Accounts.Repository.changeset(%Accounts.Repository{})
        |> Ecto.Changeset.add_error(:name, inspect(error))
        render(conn, "new.html",
          changeset: changeset,
          users: users,
          licenses: build_list_licenses())
      {:error, :repository, %Ecto.Changeset{} = changeset, _} ->
        render(conn, "new.html",
          changeset: changeset,
          users: users,
          licenses: build_list_licenses())
      {:error, _, error, _} ->
        changeset = Accounts.Repository.changeset(%Accounts.Repository{})
        |> Ecto.Changeset.add_error(:name, inspect(error))
        render(conn, "new.html",
          changeset: changeset,
          users: users,
          licenses: build_list_licenses())
    end
  end

  def show(conn, %{"id" => id}) do
    repository = Accounts.get_repository!(id)
    render(conn, "show.html", repository: repository)
  end

  def edit(conn, %{"id" => id}) do
    repository = Accounts.get_repository!(conn.assigns[:current_user], id)
    collaborations = Accounts.list_collaborations(repository)
    pushmirrors = Repositories.list_push_mirrors(repository)
    changeset = Accounts.change_repository(repository)
    changeset_pushmirror = Repositories.change_push_mirror(
      %Repositories.PushMirror{repository_id: repository.id}
    )
    
    render(conn, "edit.html", repository: repository,
      changeset: changeset,
      changeset_pushmirror: changeset_pushmirror,
      sources_pushmirror: @sources_pushmirror,
      pushmirrors: pushmirrors,
      collaborations: collaborations)
  end

  def update(conn, %{"id" => id, "repository" => params}) do
    repository = Accounts.get_repository!(conn.assigns[:current_user], id)
    with_owner_params = Map.put(params, "owner_id", conn.assigns[:current_user].id)
    collaborations = Accounts.list_collaborations(repository)
    pushmirrors = Repositories.list_push_mirrors(repository)
    changeset_pushmirror = Repositories.change_push_mirror(
      %Repositories.PushMirror{repository_id: repository.id}
    )

    case Accounts.update_repository(repository, with_owner_params) do
      {:ok, repository} ->
        conn
        |> put_flash(:info, "Repository updated successfully.")
        |> redirect(to: "/dashboard")
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", repository: repository,
          changeset: changeset, changeset_pushmirror: changeset_pushmirror,
          sources_pushmirror: @sources_pushmirror,
          pushmirrors: pushmirrors,
          collaborations: collaborations)
    end
  end

  def delete_repository(conn, %{"repository_id" => id, "repository" => params}) do
    repository = Accounts.get_repository!(conn.assigns[:current_user], id)
    changeset = Accounts.change_repository(repository)
    collaborations = Accounts.list_collaborations(repository)
    pushmirrors = Repositories.list_push_mirrors(repository)
    changeset_pushmirror = Repositories.change_push_mirror(
      %Repositories.PushMirror{repository_id: repository.id}
    )

    if repository.name == String.trim(params["confirm_name"]) do
      {:ok, _} = Accounts.delete_repository(repository)
      {:ok, ctx} = Accounts.context_repository(repository)
      {:ok, _} = Efossils.Command.delete_repository(ctx)
      conn
      |> put_flash(:info, "Repository delete successfully.")
      |> redirect(to: "/dashboard")
    else
      Plug.Conn.assign(conn, :delete_error, "Please verify")
      |> render("edit.html", repository: repository,
      changeset: changeset,
      changeset_pushmirror: changeset_pushmirror,
      sources_pushmirror: @sources_pushmirror,
      pushmirrors: pushmirrors,
      collaborations: collaborations)
    end
  end

  def pushmirror_create(conn, %{"push_mirror" => pushmirror_params}) do
    repository = Accounts.get_repository!(conn.assigns[:current_user], pushmirror_params["repository_id"])
    changeset = Accounts.change_repository(repository)
    changeset_pushmirror = Repositories.change_push_mirror(
      %Repositories.PushMirror{repository_id: repository.id}
    )
    pushmirrors = Repositories.list_push_mirrors(repository)
    collaborations = Accounts.list_collaborations(repository)


    case Repositories.create_push_mirror(pushmirror_params) do
      {:ok, pushmirror} ->
        pushmirrors = Repositories.list_push_mirrors(repository)
        conn
        |> redirect(to: repository_path(conn, :edit, repository))
      {:error, %Ecto.Changeset{} = changeset_pushmirror} ->
        conn
        |> render("edit.html", repository: repository,
        changeset: changeset,
        changeset_pushmirror: changeset_pushmirror,
        pushmirrors: pushmirrors,
        sources_pushmirror: @sources_pushmirror,
        collaborations: collaborations)
    end
  end

  def pushmirror_delete(conn, %{"repository_id" => repository_id, "push_mirror_id" => id}) do
    repository = Accounts.get_repository!(conn.assigns[:current_user], repository_id)
    pushmirror = Repositories.get_push_mirror!(id)
    Repositories.delete_push_mirror(pushmirror)
    conn
    |> redirect(to: repository_path(conn, :edit, repository))
  end

  def collaboration_create(conn, %{"repository_id" => id, "username" => username}) do
    repository = Accounts.get_repository!(conn.assigns[:current_user], id)
    changeset = Accounts.change_repository(repository)

lib/efossils_web/views/repository_view.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.RepositoryView do
  use EfossilsWeb, :view
end

lib/efossils_web/templates/repository/edit.html.eex
<!--
     # Efossils -- a multirepository for fossil-scm
     # Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
     #
     # This file is part of Efossils.
     #
     # Efossils is free software: you can redistribute it and/or modify
     # it under the terms of the GNU Affero General Public License as
     # published by the Free Software Foundation, either version 3 of the
     # License, or (at your option) any later version.
     #
     # Efossils is distributed in the hope that it will be useful,
     # but WITHOUT ANY WARRANTY; without even the implied warranty of
     # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     # GNU Affero General Public License for more details.
     #
     # You should have received a copy of the GNU Affero General Public License
     # along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
<%= form_for @changeset, repository_path(@conn, :update, @repository), [class: "ui form segment"], fn f -> %>
<h4 class="ui right floated header">General</h4>
<div class="ui clearing divider"></div>
<%= if @changeset.action do %>
  <div class="ui red message">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>
<div class="ui list">
  <div class="item">
    project-code: <%= Efossils.Accounts.repository_project_code(@repository)%>
  </div>
</div>
<div class="inline field">
  <div class="ui checkbox">
    <%= checkbox f, :is_private %>
    <%= label f, :is_private %>
  </div>
</div>

<div class="field">
  <%= label f, :description %>
  <%= textarea f, :description %>
</div>
<%= submit gettext("Update"), class: "ui primary submit button" %>
<% end %>

<%= form_for @conn, repository_collaboration_path(@conn, :collaboration_create, @repository), [class: "ui form segment"], fn f -> %>
<h4 class="ui right floated header">Collaboration</h4>
<div class="ui clearing divider"></div>
<div class="ui two column grid">
  <div class="column">
  <%= if message = @conn.assigns[:collaboration_error] do %>
    <div class="ui red message">
      <p><%= message %></p>
    </div>
  <% end %>
Please type username.

  <div class="ui search">
      <%= text_input f, :username, placeholder: "Username", class: "prompt" %>
    <div class="results"></div>
  </div>

  <%= submit gettext("Add"), class: "ui green submit button" %>
  </div>
  <div class="column">
    <div class="ui list">
    <%= for colab <- @collaborations do %>
      <div class="item">
        <i class="left floated octicon octicon-person"></i>
        <div class="right content">
          <%= colab.user.nickname %>
          <%= link "X", to: repository_collaboration_path(@conn, :collaboration_delete, @repository, colab.user.id), method: :delete, data: [confirm: gettext("Are you sure?")] %>
        </div>
      </div>
    <% end %>
    </div>
  </div>
</div>
<% end %>

<%= form_for @changeset_pushmirror, repository_pushmirror_path(@conn, :pushmirror_create, @repository), [class: "ui form segment"], fn f -> %>
<h4 class="ui right floated header">Push Mirrors</h4>
<div class="ui clearing divider"></div>
<%= if message = @conn.assigns[:delete_error] do %>
  <div class="ui red message">
    <p><%= message %></p>
  </div>
<% end %>
<div class="ui two column grid">
  <div class="column">
    <%= hidden_input f, :repository_id %>

    <div class="required field" >
     <%= label f, :source %>
     <%= select f, :source, @sources_pushmirror %>
     <%= if message = f.errors[:source] do %>
       <div class="ui red message"><%= message |> elem(0) %></div>
     <% end %>
    </div>

    <div class="required field" >
     <%= label f, :name %>
     <%= text_input f, :name, required: false %>
     <%= if message = f.errors[:name] do %>
     <div class="ui red message"><%= message |> elem(0) %></div>
     <% end %>
    </div>

    <div class="required field" >
     <%= label f, :url %>
     <%= text_input f, :url, required: true %>
     <%= if message = f.errors[:url] do %>
     <div class="ui red message"><%= message |> elem(0) %></div>
     <% end %>
    </div>
  </div>

  <div class="column">
    <div class="ui list">
      <%= for pushmirror <- @pushmirrors do %>
        <div class="item">
          <div class="content">
              <div class="header"><%= pushmirror.name %> source: <%= pushmirror.source %>

              <%= link  to: repository_pushmirror_path(@conn, :pushmirror_delete, @repository, pushmirror.id), method: :delete, data: [confirm: "Are you user?"] do %>
                <i class="octicon octicon-x"></i>
              <% end %>
            </div>
            <div class="description">
              <%= gettext("Last Sync")%>: <%= pushmirror.last_sync %> <%= gettext("Status") %>: <%= pushmirror.last_sync_status %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>
<%= submit gettext("Add"), class: "ui green submit button" %>
<% end %>

<%= form_for @changeset, repository_settings_path(@conn, :delete_repository, @repository), [class: "ui form segment"], fn f -> %>
<h4 class="ui right floated header">Delete</h4>
<div class="ui clearing divider"></div>
<%= if message = @conn.assigns[:delete_error] do %>
  <div class="ui red message">
    <p><%= message %></p>
  </div>
<% end %>
Please type repository name for permanent delete for <b><%= @repository.name %>.
<div class="field">
  <%= label f, :confirm_name %>
  <%= text_input f, :confirm_name, placeholder: "Repository Name..." %>
  <%= error_tag f, :confirm_name %>
</div>
<%= submit gettext("Delete"), class: "ui red submit button" %>

<% end %>

lib/efossils_web/templates/repository/migrate.html.eex
<!--
     # Efossils -- a multirepository for fossil-scm
     # Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
     #
     # This file is part of Efossils.
     #
     # Efossils is free software: you can redistribute it and/or modify
     # it under the terms of the GNU Affero General Public License as
     # published by the Free Software Foundation, either version 3 of the
     # License, or (at your option) any later version.
     #
     # Efossils is distributed in the hope that it will be useful,
     # but WITHOUT ANY WARRANTY; without even the implied warranty of
     # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     # GNU Affero General Public License for more details.
     #
     # You should have received a copy of the GNU Affero General Public License
     # along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
<%= form_for @changeset, migration_path(@conn, :migrate_create), [class: "ui form segment"], fn f -> %>
<h4 class="ui right floated header"><%= gettext("Migration") %></h4>

<%= if @changeset.action do %>
  <div class="ui red message">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>

<div class="field">
  <%= label f, :source %>
  <%= select f, :source, @sources %>
</div>

<div class="field">
  <%= label f, :source_url %>
  <%= text_input f, :source_url %>
  <%= if message = @changeset.errors[:source_url] do %>
    <div class="ui red message"><%= message |> elem(0) %></div>
  <% end %>
</div>

<div class="ui accordion">
  <div class="title">
    <i class="dropdown icon"></i>
    Autentication
  </div>
  <div class="content">
    <div class="field">
  <%= label f, :source_username %>
  <%= text_input f, :source_username %>
    </div>
    <div class="field">
  <%= label f, :source_password %>
  <%= password_input f, :source_password %>
    </div>
  </div>
</div>

<div class="ui fitted divider"></div>

<div class="field">
  <%= label f, :owner %>
  <%= select f, :owner_id, @users %>
  <%= if message = f.errors[:owner] do %>
    <div class="ui message"><%= message |> elem(0) %></div>
  <% end %>
</div>

<div class="field" >
  <%= label f, :name %>
  <%= text_input f, :name %>
  <%= if message = f.errors[:name] do %>
    <div class="ui message"><%= message |> elem(0) %></div>
  <% end %>
</div>

<div class="inline field">
  <div class="ui checkbox">
    <%= checkbox f, :is_private %>
    <%= label f, :is_private %>
  </div>
</div>

<div class="field">
  <%= label f, :description %>
  <%= textarea f, :description %>
</div>

<div class="field">
  <%= label f, :license %>
  <%= select f, :license, @licenses %>
</div>

<div class="inline field">
  <div class="ui checkbox">
    <%= checkbox f, :is_mirror %>
    <%= label f, :is_mirror, title: 'Only for Fossil' %>
  </div>
</div>

<%= submit gettext("Migrate"), class: "ui primary submit button" %>
<% end %>

lib/efossils_web/templates/repository/new.html.eex
<!--
     # Efossils -- a multirepository for fossil-scm
     # Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
     #
     # This file is part of Efossils.
     #
     # Efossils is free software: you can redistribute it and/or modify
     # it under the terms of the GNU Affero General Public License as
     # published by the Free Software Foundation, either version 3 of the
     # License, or (at your option) any later version.
     #
     # Efossils is distributed in the hope that it will be useful,
     # but WITHOUT ANY WARRANTY; without even the implied warranty of
     # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     # GNU Affero General Public License for more details.
     #
     # You should have received a copy of the GNU Affero General Public License
     # along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
<%= form_for @changeset, repository_path(@conn, :create), [class: "ui form segment"], fn f -> %>
<h4 class="ui right floated header"><%= gettext("Repository") %></h4>
<%= if @changeset.action do %>
  <div class="ui red message">
    <p>Oops, something went wrong! Please check the errors below.</p>
  </div>
<% end %>

<div class="required field">
  <%= label f, :owner %>
  <%= select f, :owner_id, @users %>
  <%= if message = f.errors[:owner_id] do %>
    <div class="ui red message"><%= message |> elem(0) %></div>
  <% end %>
</div>

<div class="required field" >
  <%= label f, :name %>
  <%= text_input f, :name, required: true %>
  <%= if message = f.errors[:name] do %>
  <div class="ui red message"><%= message |> elem(0) %></div>
  <% end %>
</div>

<div class="inline field">
  <div class="ui checkbox">
    <%= checkbox f, :is_private %>
    <%= label f, :is_private %>
  </div>
</div>

<div class="field">
  <%= label f, :description %>
  <%= textarea f, :description %>
</div>

<div class="field">
  <%= label f, :license %>
  <%= select f, :license, @licenses %>
</div>

<div class="ui styled accordion">
  <div class="title">
    <i class="dropdown icon"></i>
    <%= gettext("Settings")%>
  </div>
   <div class="content">
     <div class="transition hidden">
       <div class="field">
        <%= label f, :project_code %>
        <%= text_input f, :project_code%>
       </div>
        <%= gettext("Override project code (Optional, but may be needed if pushing an already created repo to Efossils.")%>
    </div>
  </div>
</div>

<%= submit gettext("Create Repository"), class: "ui primary submit button" %>
<% end %>