lib/efossils_web/router.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.Router do
  use EfossilsWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :efossils

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout_from_session
  end
  
  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler 
    plug :put_layout_from_session
  end

  pipeline :put_session do
    plug :fetch_session
  end
  
  scope "/" do
    pipe_through :browser
    pow_routes()
    pow_extension_routes()
  end
  
  scope "/" do
    pipe_through :protected
    pow_routes()
    pow_extension_routes()
  end

  scope "/fossil", EfossilsWeb do
    pipe_through :put_session
    forward "/", Proxy.Plug
  end
  
  scope "/", EfossilsWeb do
    pipe_through :browser # Use the default browser stack
    
    get "/", PageController, :index

    get "/explore/repositories", ExploreRepositoriesController, :index
    get "/explore/repositories/:username", ExploreRepositoriesController, :index_by_username
  end

  scope "/", EfossilsWeb do
    pipe_through :protected

    get "/profile", ProfileController, :index
    put "/profile", ProfileController, :update
    get "/dashboard", PageController, :dashboard
    get "/", PageController, :dashboard
    resources "/repositories", RepositoryController do
      put "/delete", RepositoryController, :delete_repository, as: :settings
      post "/collaboration/add", RepositoryController, :collaboration_create, as: :collaboration
      delete "/collaboration/:user_id/delete", RepositoryController, :collaboration_delete, as: :collaboration
      post "/pushmirror/add", RepositoryController, :pushmirror_create, as: :pushmirror
      delete "/pushmirror/:push_mirror_id/delete", RepositoryController, :pushmirror_delete, as: :pushmirror
    end

    get "/migrate/repository", RepositoryController, :migrate_new, as: :migration
    post "/migrate/repository", RepositoryController, :migrate_create, as: :migration
  end

  scope "/api/v1", EfossilsWeb do
    pipe_through :protected
    get "/search/user", Api.V1.SearchController, :user
  end
  
  defp put_layout_from_session(conn, _) do
    if conn.assigns[:current_user] do
      Phoenix.Controller.put_layout(conn, {EfossilsWeb.Phoenix.LayoutView, :app})
    else
      Phoenix.Controller.put_layout(conn, {EfossilsWeb.Phoenix.LayoutView, :page})
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", EfossilsWeb do
  #   pipe_through :api
  # end
end

lib/efossils_web/views/layout_view.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.LayoutView do
  use EfossilsWeb, :view
end

# Esto es requerido por 'pow' ya que sin esto
# no permite usar los layouts
defmodule EfossilsWeb.Phoenix.LayoutView do
  use Phoenix.View, root: "lib/efossils_web/templates",
    path: "layout",
    namespace: EfossilsWeb
  # Import convenience functions from controllers
  import Phoenix.Controller, only: [get_flash: 2, view_module: 1]

  # Use all HTML functionality (forms, tags, etc)
  use Phoenix.HTML

  import EfossilsWeb.Router.Helpers
  import EfossilsWeb.ErrorHelpers
  import EfossilsWeb.Gettext
end

lib/efossils_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <!--
         # Efossils -- a multirepository for fossil-scm
         # Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
         #
         # This file is part of Efossils.
         #
         # Efossils is free software: you can redistribute it and/or modify
         # it under the terms of the GNU Affero General Public License as
         # published by the Free Software Foundation, either version 3 of the
         # License, or (at your option) any later version.
         #
         # Efossils is distributed in the hope that it will be useful,
         # but WITHOUT ANY WARRANTY; without even the implied warranty of
         # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         # GNU Affero General Public License for more details.
         #
         # You should have received a copy of the GNU Affero General Public License
         # along with this program.  If not, see <https://www.gnu.org/licenses/>.
    -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Multirepository fossils">
    <meta name="author" content="Jovany Leandro G.C <bit4bit@riseup.net>">
    <%= if @conn.assigns[:user_token], do: tag :meta, name: "user_token", content: @conn.assigns.user_token %>
    <title>Efossils!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="full height">

      <div class="ui text attached stackable menu">
        <div class="ui container">
          <a class="item" href="/dashboard">
            <i class="octicon octicon-home"></i><%= gettext "Dashboard"%>
          </a>
          <a class="item" href="/explore/repositories"><%= gettext "Explore"%></a>
          <a class="item" href="/profile"><%= "Profile" %></a>
        </div>
        <div class="ui right dropdown item">
          More
          <i class="dropdown icon"></i>
          <div class="menu">
            <%= link(gettext("Create Repository"), to: repository_path(@conn, :new), class: "item") %>
            <%= link(gettext("Migrate Repository"), to: migration_path(@conn, :migrate_new), class: "item") %>
          </div>
        </div>
        <div class="right item">
          <%= link(gettext("Logout"), to: pow_session_path(@conn, :delete), method: :delete, class: "ui button")%>
        </div>
      </div>



      <div class="ui container">
        <%= if message = get_flash(@conn, :info) do %>
          <p class="ignored info ui message" role="message"><%= message %></p>
        <% end %>
        <%= if message = get_flash(@conn, :error) do %>
          <p class="danger ui message" role="message"><%= message%></p>
        <% end %>
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>
    </div> <!-- /container -->
    <footer>
      <%= render "footer.html" %>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/efossils_web/templates/layout/footer.html.eex
<!--
     # Efossils -- a multirepository for fossil-scm
     # Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
     #
     # This file is part of Efossils.
     #
     # Efossils is free software: you can redistribute it and/or modify
     # it under the terms of the GNU Affero General Public License as
     # published by the Free Software Foundation, either version 3 of the
     # License, or (at your option) any later version.
     #
     # Efossils is distributed in the hope that it will be useful,
     # but WITHOUT ANY WARRANTY; without even the implied warranty of
     # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     # GNU Affero General Public License for more details.
     #
     # You should have received a copy of the GNU Affero General Public License
     # along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
<div class="ui borderless menu">
  <div class="ui left item ">
          Efossils v<%= Keyword.get(Mix.Project.config, :version) %> -- AGPL 3+ <a href="https://chiselapp.com/user/bit4bit/repository/efossils">Get this source</a>
  </div>
  <div class="ui right item links">
    
  </div>
</div>

lib/efossils_web/templates/layout/page.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <!--
         # Efossils -- a multirepository for fossil-scm
         # Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
         #
         # This file is part of Efossils.
         #
         # Efossils is free software: you can redistribute it and/or modify
         # it under the terms of the GNU Affero General Public License as
         # published by the Free Software Foundation, either version 3 of the
         # License, or (at your option) any later version.
         #
         # Efossils is distributed in the hope that it will be useful,
         # but WITHOUT ANY WARRANTY; without even the implied warranty of
         # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
         # GNU Affero General Public License for more details.
         #
         # You should have received a copy of the GNU Affero General Public License
         # along with this program.  If not, see <https://www.gnu.org/licenses/>.
    -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Multirepository fossils">
    <meta name="author" content="Jovany Leandro G.C <bit4bit@riseup.net>">

    <title>Efossils!</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div class="full height">

      <div class="ui text attached stackable menu">
        <div class="ui container">
          <a class="item" href="/">
            <i class="octicon octicon-home"></i><%= gettext "Home"%>
          </a>
          <a class="item" href="/explore/repositories"><%= gettext "Explore"%></a>
        </div>
        <div class="right item">
          <a class="item" href="<%= pow_session_path(@conn, :new) %>">
            <i class="octicon octicon-sign-in"></i><%= gettext "Sign In" %>
          </a>
        </div>
      </div>


      <div class="ui container">
        
        <%= if message = get_flash(@conn, :info) do %>
          <p class="ignored info ui message" role="message"><%= message %></p>
        <% end %>
        <%= if message = get_flash(@conn, :error) do %>
          <p class="danger ui message" role="message"><%= message%></p>
        <% end %>
        <main role="main">
          <%= render @view_module, @view_template, assigns %>
        </main>
      </div>
    </div> <!-- /container -->
    <footer>
      <%= render "footer.html" %>
    </footer>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>