lib/efossils_web/router.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.Router do
  use EfossilsWeb, :router
  use Pow.Phoenix.Router
  use Pow.Extension.Phoenix.Router, otp_app: :efossils

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :put_layout_from_session
  end
  
  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler 
    plug :put_layout_from_session
  end

  pipeline :put_session do
    plug :fetch_session
  end
  
  scope "/" do
    pipe_through :browser
    pow_routes()
    pow_extension_routes()
  end
  
  scope "/" do
    pipe_through :protected
    pow_routes()
    pow_extension_routes()
  end

  scope "/fossil", EfossilsWeb do
    pipe_through :put_session
    forward "/", Proxy.Plug
  end
  
  scope "/", EfossilsWeb do
    pipe_through :browser # Use the default browser stack
    
    get "/", PageController, :index

    get "/explore/repositories", ExploreRepositoriesController, :index
    get "/explore/repositories/:username", ExploreRepositoriesController, :index_by_username
  end

  scope "/", EfossilsWeb do
    pipe_through :protected

    get "/profile", ProfileController, :index
    put "/profile", ProfileController, :update
    get "/dashboard", PageController, :dashboard
    get "/", PageController, :dashboard
    resources "/repositories", RepositoryController do
      put "/delete", RepositoryController, :delete_repository, as: :settings
      post "/collaboration/add", RepositoryController, :collaboration_create, as: :collaboration
      delete "/collaboration/:user_id/delete", RepositoryController, :collaboration_delete, as: :collaboration
      post "/pushmirror/add", RepositoryController, :pushmirror_create, as: :pushmirror
      delete "/pushmirror/:push_mirror_id/delete", RepositoryController, :pushmirror_delete, as: :pushmirror
    end

    get "/migrate/repository", RepositoryController, :migrate_new, as: :migration
    post "/migrate/repository", RepositoryController, :migrate_create, as: :migration
  end

  scope "/api/v1", EfossilsWeb do
    pipe_through :protected
    get "/search/user", Api.V1.SearchController, :user
  end
  
  defp put_layout_from_session(conn, _) do
    if conn.assigns[:current_user] do
      Phoenix.Controller.put_layout(conn, {EfossilsWeb.Phoenix.LayoutView, :app})
    else
      Phoenix.Controller.put_layout(conn, {EfossilsWeb.Phoenix.LayoutView, :page})
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", EfossilsWeb do
  #   pipe_through :api
  # end
end

lib/efossils_web/controllers/explore_repositories_controller.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.ExploreRepositoriesController do
  use EfossilsWeb, :controller
  import Ecto.Query, warn: false
  alias Efossils.Accounts

  def index_by_username(conn, params) do
    index(conn, params)
  end
  
  def index(conn, params) do
    order_by = case params["order_by"] do
                 "license" ->
                   [asc: :license]
                 "updated-at" ->
                   [desc: :updated_at]
                 _ ->
                   [desc: :inserted_at]
               end

    filter = case params["license"] do
               empty when is_nil(empty) or empty == "" -> []
               license -> [license: license]
             end

    filter_by_username = case params["username"] do
                           empty when is_nil(empty) or empty == "" -> []
                           username ->
                             case Accounts.get_user_by_name(username) do
                               nil -> [owner_id: 0]
                               user -> [owner_id: user.id]
                             end
                         end
    
    repositories = search(Efossils.Accounts.Repository, params["search"])
    |> preload([:base_repository, :owner])
    |> order_by(^order_by)
    |> where(^filter)
    |> where(^filter_by_username)
    |> Efossils.Repo.paginate(params)
    render conn, "index.html", repositories: repositories,
      orderBy: params["order_by"],
      license: params["license"],
      licenses: build_list_licenses()
  end

  defp search(query, ""), do: search(query, nil)
  defp search(query, nil), do: from(u in query, where: u.is_private == false)
  defp search(query, search_term) when is_binary(search_term) do
    from(u in query,                                                
      where: fragment("to_tsvector('english', ? || ?) @@ to_tsquery('english', ?)", u.name, u.description, ^search_term)
    )
  end
  
  defp build_list_licenses() do
    Enum.map(Accounts.Repository.licenses, fn {code, license} ->
      {license.name, code}
    end)
  end

end

lib/efossils_web/views/explore_repositories_view.ex
# Efossils -- a multirepository for fossil-scm
# Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
#
# This file is part of Efossils.
#
# Efossils is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# Efossils is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

defmodule EfossilsWeb.ExploreRepositoriesView do
  use EfossilsWeb, :view
  import Scrivener.HTML
  import EfossilsWeb.EfossilsHelper  
end

lib/efossils_web/templates/explore_repositories/index.html.eex
<!--
     # Efossils -- a multirepository for fossil-scm
     # Copyright (C) 2018  Jovany Leandro G.C <bit4bit@riseup.net>
     #
     # This file is part of Efossils.
     #
     # Efossils is free software: you can redistribute it and/or modify
     # it under the terms of the GNU Affero General Public License as
     # published by the Free Software Foundation, either version 3 of the
     # License, or (at your option) any later version.
     #
     # Efossils is distributed in the hope that it will be useful,
     # but WITHOUT ANY WARRANTY; without even the implied warranty of
     # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     # GNU Affero General Public License for more details.
     #
     # You should have received a copy of the GNU Affero General Public License
     # along with this program.  If not, see <https://www.gnu.org/licenses/>.
-->
<form action="<%=  explore_repositories_path(@conn, :index) %>" method="get">
  <div class="ui action input">
    <input placeholder="Search..." type="text" name="search">
    <button class="ui button"><i class="octicon octicon-search"></i></button>
  </div>
  <div class="ui action input selection dropdown">
    <input name="order_by" type="hidden" value="<%= @orderBy %>">
    <i class="dropdown icon"> </i>
    <div class="default text">Order By</div>
    <div class="menu">
      <div class="item" data-value="inserted-at">Inserted At</div>
      <div class="item" data-value="updated-at">Updated At</div>
      <div class="item" data-value="license">License</div>
    </div>
  </div>

  <div class="ui action input selection dropdown">
    <input name="license" type="hidden" value="<%= @license %>">
    <i class="dropdown icon"> </i>
    <div class="default text">License</div>
    <div class="menu">
      <div class="item" data-value="">All</div>
      <%= for {key,val} <- @licenses do %>
      <div class="item" data-value="<%= val %>"><%= key %></div>
      <% end %>
    </div>
  </div>

</form>
<div class="ui three column grid">
  <%=  for repository <- @repositories do %>
    <div class="column">
      <div class="ui fluid card">

        <div class="content">
          <div class="ui teal right ribbon label"><%= Application.get_env(:efossils, :federated_name) %>
          </div>

          <div class="header">
            <div class="ui <%= repository.owner.color_css %> left ribbon label" style="">
              <%= repository_username(repository) %>
            </div>

<%= repository.nickname %>
          </div>
          <div class="description">
            <div class="ui two column grid">
              <div class="column">
                <span>
                  <i class="octicon octicon-person"></i>
                  <%= repository_num_collaborators(repository) %> Collaborators
                </span>
              </div>
              <div class="column">
                <i class="octicon octicon-megaphone"></i> <%=  repository.license %>
              </div>
            </div>
          </div>
          <div class="ui divider"></div>
          <div class="text">
            <pre style="white-space: pre-wrap;">
            <%= repository.description %>
            </pre>
          </div>
        </div>
        <div class="extra content">
          <a href="<%= EfossilsWeb.Utils.fossil_path("xfer", repository.owner, repository) %>" onclick="return false;" title="Copy this link, then run *fossil clone <url>*"><i class="left floated octicon octicon-clippy"></i></a>
          <a target="repository-<%= repository.id %>" href="<%= EfossilsWeb.Utils.fossil_path("index", repository.owner, repository) %>" class="ui button">
            Open
          </a>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= pagination_links @repositories, order_by: @orderBy, license: @license %>